### ISSUE TITLE
Brief description of projects

### ISSUE THREAD

**Issue by zmrfzn** [yanpitangui/netcore-api-boilerplate#5]
Repository template looks really useful. 

Although, it would be helpful to get started with it if you could include brief description of individual projects

**Comment by yanpitangui** [comment]
Hello, thanks for the feedback! I've created a pull request that hopefully helps with this issue.
Thank you!

**Comment by zmrfzn** [comment]
one other question i had is.

i see domain and domain core using dot-net standard 2.1, in that case it is not using only Dotnetcore 3.1?

**Comment by yanpitangui** [comment]
@zmrfzn, As these projects are class libraries with simple classes and interfaces, it doesn't really matter if they are standard 2.1 or core, as they will not be using (as of now) any external package. If you want to change it for your purposes, you can. Soon i will be updating the project to core to make it more standardized.  .Net Core is a implementation of .Net standard for web, console and cloud applications. You can read more here: [https://andrewlock.net/converting-a-netstandard-2-library-to-netcore-3/](https://andrewlock.net/converting-a-netstandard-2-library-to-netcore-3/)
