### ISSUE TITLE
[BUG] misspelled word in the readme

### ISSUE THREAD

**Issue by higorrebell0** [yanpitangui/netcore-api-boilerplate#8]
**Misspelled word in the readme**
In the Docker session of the Readme, the Docker compose command is misspelled.

**Expected behavior**
 `docker-compose up -d`

**Screenshots**
![image](https://user-images.githubusercontent.com/45660996/98752610-476d8a00-23a1-11eb-8626-6006d8dc35d2.png)

 - OS: Windows 10 - OS Build 18363.1139
 - Visual Studio Professional 2019
 - .Net SDK 3.0

**Comment by yanpitangui** [comment]
Hi, thank you for you contribution!
The issue is already adressed and has been fixed.
